pub use add_letters::add_letters;
pub use alphabet_position::alphabet_position;
pub use alternating_case::to_alternating_case;
pub use array_diff::array_diff;
pub use camel_case::camel_case;
pub use common_denominators::convert_fracts;
pub use complementary_dna::dna_strand;
pub use create_phone_number::create_phone_number;
pub use deodorant_evaporator::evaporator;
pub use duplicate_encoder::duplicate_encode;
pub use factorial_decomposition::decomp;
pub use find_digit::find_digit;
pub use good_vs_evil::good_vs_evil;
pub use john_and_ann::{ann, john, sum_ann, sum_john};
pub use josephus_survivor::josephus_survivor;
pub use rainfall::{mean, variance};
pub use remove_duplicate_words::remove_duplicate_words;
pub use rot13::rot13;
pub use shortest_word::find_short;
pub use speed_control::gps;
pub use squared_strings::{hor_mirror, oper, vert_mirror};
pub use str_ends_with::solution;
pub use simple_assembler::simple_assembler;
pub use algebraic_list::Cons;
pub use differentiation::diff;

mod str_ends_with;
mod speed_control;
mod squared_strings;
mod complementary_dna;
mod find_digit;
mod shortest_word;
mod alphabet_position;
mod deodorant_evaporator;
mod camel_case;
mod remove_duplicate_words;
mod add_letters;
mod create_phone_number;
mod good_vs_evil;
mod common_denominators;
mod josephus_survivor;
mod john_and_ann;
mod factorial_decomposition;
mod alternating_case;
mod array_diff;
mod duplicate_encoder;
mod rainfall;
mod rot13;
mod simple_assembler;
mod algebraic_list;
mod differentiation;